# Generated by Django 5.1.1 on 2026-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('data_entry', 'Data Entry Operator'), ('analyst', 'Analyst'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('admin', 'Administrator')], default='data_entry', max_length=30),
        ),
    ]
