# Generated by Django 5.1.1 on 2026-03-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_type', models.CharField(help_text='Type of fuel used', max_length=100)),
                ('fuel_amount', models.FloatField(help_text='Amount of fuel used')),
                ('emission_factor', models.FloatField(help_text='Emission factor for the fuel type')),
                ('co2_emission', models.FloatField(help_text='Calculated CO2 emission in kg')),
                ('methane_emission', models.FloatField(default=0, help_text='Methane emission in kg')),
                ('nitrous_oxide', models.FloatField(default=0, help_text='Nitrous oxide emission in kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_emissions', to='industries.department')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_emissions', to='industries.industry')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('industry', 'date', 'fuel_type')},
            },
        ),
    ]
