# Generated by Django 5.1.1 on 2026-03-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carbonemission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='co2_emission',
            field=models.FloatField(default=0, help_text='Calculated CO2 emission in kg'),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='fuel_type',
            field=models.CharField(help_text='Type of fuel used (Diesel, Petrol, Gas etc.)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='carbonemission',
            index=models.Index(fields=['industry'], name='emissions_c_industr_bb4b12_idx'),
        ),
        migrations.AddIndex(
            model_name='carbonemission',
            index=models.Index(fields=['department'], name='emissions_c_departm_e51787_idx'),
        ),
        migrations.AddIndex(
            model_name='carbonemission',
            index=models.Index(fields=['date'], name='emissions_c_date_541993_idx'),
        ),
        migrations.AddConstraint(
            model_name='carbonemission',
            constraint=models.UniqueConstraint(fields=('industry', 'date', 'fuel_type'), name='unique_industry_fuel_emission'),
        ),
    ]
