# Generated by Django 5.1.1 on 2026-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_carbonemission_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carbonemission',
            name='emissions_c_industr_bb4b12_idx',
        ),
        migrations.RemoveIndex(
            model_name='carbonemission',
            name='emissions_c_departm_e51787_idx',
        ),
        migrations.RemoveIndex(
            model_name='carbonemission',
            name='emissions_c_date_541993_idx',
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='co2_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='emission_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='fuel_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='methane_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='nitrous_oxide',
            field=models.FloatField(default=0),
        ),
    ]
