# Generated by Django 5.1.1 on 2026-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_remove_carbonemission_emissions_c_industr_bb4b12_idx_and_more'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonemission',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='carbonemission',
            index=models.Index(fields=['industry', 'date'], name='emissions_c_industr_d36899_idx'),
        ),
    ]
