# Generated by Django 5.1.1 on 2026-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_alter_carbonemission_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carbonemission',
            name='emissions_c_industr_d36899_idx',
        ),
        migrations.AlterField(
            model_name='carbonemission',
            name='date',
            field=models.DateField(),
        ),
    ]
