# Generated by Django 6.0.3 on 2026-05-05 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0007_create_uploadaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='carbonemission',
            new_name='emissions_c_date_541993_idx',
            old_name='emissions_date_idx',
        ),
        migrations.RenameIndex(
            model_name='carbonemission',
            new_name='emissions_c_industr_d36899_idx',
            old_name='emissions_industry_date_idx',
        ),
        migrations.AlterField(
            model_name='uploadaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadaudit',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
