# Generated by Django 6.0.3 on 2026-03-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_type', models.CharField(help_text='Diesel, Petrol, Natural Gas, Coal, etc', max_length=100)),
                ('quantity', models.FloatField(help_text='Fuel quantity in liters or kg')),
                ('cost', models.FloatField()),
                ('carbon_emission_factor', models.FloatField(help_text='Emission factor for this fuel')),
                ('total_emission', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_fuel', to='industries.department')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_usage', to='industries.industry')),
            ],
        ),
    ]
