# Generated by Django 6.0.3 on 2026-05-05 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('co2_kg_per_unit', models.FloatField(default=0)),
                ('ch4_kg_per_unit', models.FloatField(default=0)),
                ('n2o_kg_per_unit', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
            },
        ),
        migrations.CreateModel(
            name='AQIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('pm25', models.FloatField(default=0)),
                ('pm10', models.FloatField(default=0)),
                ('no2', models.FloatField(default=0)),
                ('so2', models.FloatField(default=0)),
                ('co', models.FloatField(default=0)),
                ('aqi', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('computed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['industry', 'date'], name='monitoring__industr_e2ea1f_idx')],
                'unique_together': {('industry', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CarbonEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('co2_emission', models.FloatField(default=0)),
                ('methane_emission', models.FloatField(default=0)),
                ('nitrous_emission', models.FloatField(default=0)),
                ('total_emission', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['industry', 'date'], name='monitoring__industr_4a66a8_idx')],
                'unique_together': {('industry', 'date')},
            },
        ),
    ]
