# Generated by Django 6.0.3 on 2026-03-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pm25', models.FloatField(help_text='PM2.5 level')),
                ('pm10', models.FloatField(help_text='PM10 level')),
                ('co2', models.FloatField(help_text='CO2 level')),
                ('no2', models.FloatField(help_text='NO2 level')),
                ('so2', models.FloatField(help_text='SO2 level')),
                ('ozone', models.FloatField(help_text='Ozone level')),
                ('aqi', models.IntegerField(help_text='Air Quality Index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_air_quality', to='industries.department')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_data', to='industries.industry')),
            ],
        ),
    ]
