# Generated by Django 6.0.3 on 2026-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airquality',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='department',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='ozone',
        ),
        migrations.AlterField(
            model_name='airquality',
            name='aqi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='co2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='no2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm10',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm25',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='so2',
            field=models.FloatField(),
        ),
    ]
