# Generated by Django 5.1.1 on 2026-03-15 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0002_remove_airquality_created_at_and_more'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airquality',
            options={'ordering': ['-date'], 'verbose_name': 'Air Quality Data', 'verbose_name_plural': 'Air Quality Data'},
        ),
        migrations.AddField(
            model_name='airquality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airquality',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_air_quality', to='industries.department'),
        ),
        migrations.AddField(
            model_name='airquality',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Humidity in %', null=True),
        ),
        migrations.AddField(
            model_name='airquality',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_data', to='industries.industry'),
        ),
        migrations.AddField(
            model_name='airquality',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in °C', null=True),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='aqi',
            field=models.IntegerField(help_text='Air Quality Index'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='co2',
            field=models.FloatField(help_text='CO2 concentration in ppm'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='no2',
            field=models.FloatField(help_text='NO2 concentration in µg/m³'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm10',
            field=models.FloatField(help_text='PM10 concentration in µg/m³'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='pm25',
            field=models.FloatField(help_text='PM2.5 concentration in µg/m³'),
        ),
        migrations.AlterField(
            model_name='airquality',
            name='so2',
            field=models.FloatField(help_text='SO2 concentration in µg/m³'),
        ),
    ]
