# Generated by Django 5.1.1 on 2026-03-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0003_alter_airquality_options_airquality_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airquality',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='airquality',
            name='temperature',
        ),
    ]
