# Generated by Django 5.1.1 on 2026-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0004_remove_airquality_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airquality',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Humidity in %', null=True),
        ),
        migrations.AddField(
            model_name='airquality',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in °C', null=True),
        ),
    ]
