# Generated by Django 6.0.3 on 2026-03-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('electricity_consumption', models.FloatField(help_text='Electricity consumption in kWh')),
                ('renewable_energy', models.FloatField(help_text='Renewable energy used in kWh')),
                ('non_renewable_energy', models.FloatField(help_text='Non renewable energy used in kWh')),
                ('total_energy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_energy', to='industries.department')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usage', to='industries.industry')),
            ],
        ),
    ]
