# Generated by Django 6.0.3 on 2026-03-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_energy', to='industries.department'),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_usage', to='industries.industry'),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='non_renewable_energy',
            field=models.FloatField(help_text='Non-renewable energy used in kWh'),
        ),
    ]
