# Generated by Django 6.0.3 on 2026-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_alter_energyusage_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='total_energy',
            field=models.FloatField(editable=False),
        ),
    ]
